# Generated by Django 6.0.7 on 2026-08-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cateog0ry',
            new_name='category',
        ),
    ]
